## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("/Users/aedenghebreselassie/Desktop/GW_Class_Folder2/Week_6/World_Weather_Analysis/Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Cap Malheureux,MU,-19.9842,57.6142,78.48,70,5,3.00,clear sky
1,1,Cape Town,ZA,-33.9258,18.4232,61.27,90,75,3.00,moderate rain
2,2,Mataura,NZ,-46.1927,168.8643,55.47,47,92,5.06,overcast clouds
3,3,Bandarbeyla,SO,9.4942,50.8122,76.21,64,5,16.08,clear sky
4,4,Salalah,OM,17.0151,54.0924,71.31,41,0,7.54,clear sky

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Cap Malheureux,MU,-19.9842,57.6142,78.48,70,5,3.00,clear sky
3,3,Bandarbeyla,SO,9.4942,50.8122,76.21,64,5,16.08,clear sky
7,7,Carnarvon,AU,-24.8667,113.6333,77.07,69,0,17.27,clear sky
11,11,Hithadhoo,MV,-0.6000,73.0833,81.27,78,100,12.30,overcast clouds
18,18,Pizarro,CO,4.9533,-77.3660,76.64,93,100,9.28,light rain
20,20,Faanui,PF,-16.4833,-151.7500,81.37,66,44,17.02,scattered clouds
23,23,Georgetown,MY,5.4112,100.3354,77.90,78,20,9.22,few clouds
24,24,Saint-Pierre,RE,-21.3393,55.4781,76.64,72,0,6.91,clear sky
25,25,Rikitea,PF,-23.1203,-134.9692,76.50,74,99,8.61,overcast clouds
28,28,Saint-Philippe,RE,-21.3585,55.7679,76.55,79,37,10.47,scattered clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                182
City                   182
Country                182
Lat                    182
Lng                    182
Max Temp               182
Humidity               182
Cloudiness             182
Wind Speed             182
Current Description    182
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
#No empty rows so will keep current df name:
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Cap Malheureux,MU,-19.9842,57.6142,78.48,70,5,3.00,clear sky
3,3,Bandarbeyla,SO,9.4942,50.8122,76.21,64,5,16.08,clear sky
7,7,Carnarvon,AU,-24.8667,113.6333,77.07,69,0,17.27,clear sky
11,11,Hithadhoo,MV,-0.6000,73.0833,81.27,78,100,12.30,overcast clouds
18,18,Pizarro,CO,4.9533,-77.3660,76.64,93,100,9.28,light rain
20,20,Faanui,PF,-16.4833,-151.7500,81.37,66,44,17.02,scattered clouds
23,23,Georgetown,MY,5.4112,100.3354,77.90,78,20,9.22,few clouds
24,24,Saint-Pierre,RE,-21.3393,55.4781,76.64,72,0,6.91,clear sky
25,25,Rikitea,PF,-23.1203,-134.9692,76.50,74,99,8.61,overcast clouds
28,28,Saint-Philippe,RE,-21.3585,55.7679,76.55,79,37,10.47,scattered clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Cap Malheureux,MU,78.48,clear sky,-19.9842,57.6142,
3,Bandarbeyla,SO,76.21,clear sky,9.4942,50.8122,
7,Carnarvon,AU,77.07,clear sky,-24.8667,113.6333,
11,Hithadhoo,MV,81.27,overcast clouds,-0.6000,73.0833,
18,Pizarro,CO,76.64,light rain,4.9533,-77.3660,
20,Faanui,PF,81.37,scattered clouds,-16.4833,-151.7500,
23,Georgetown,MY,77.90,few clouds,5.4112,100.3354,
24,Saint-Pierre,RE,76.64,clear sky,-21.3393,55.4781,
25,Rikitea,PF,76.50,overcast clouds,-23.1203,-134.9692,
28,Saint-Philippe,RE,76.55,scattered clouds,-21.3585,55.7679,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [11]:
# 7. Drop the rows where there is no Hotel Name.
nan_value = float("NaN")

In [13]:
clean_hotel_df = hotel_df
clean_hotel_df.replace("", nan_value, inplace=True)

In [14]:
clean_hotel_df.dropna(subset = ["Hotel Name"], inplace=True)

In [16]:
clean_hotel_df.sample(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
59,Kalmunai,LK,76.86,clear sky,7.4167,81.8167,VS Villa
532,Takoradi,GH,80.17,scattered clouds,4.8845,-1.7554,Raybow International Hotel
74,Port-Gentil,GA,80.56,thunderstorm with light rain,-0.7193,8.7815,Fengshui Residence
105,Axim,GH,80.37,scattered clouds,4.8699,-2.2405,Axim Beach Resort And Spa
301,Mahibadhoo,MV,82.17,scattered clouds,3.7833,72.9667,Omadhoo Inn
677,Gizo,SB,84.27,light rain,-8.1030,156.8419,Imagination Island
377,Teahupoo,PF,80.56,overcast clouds,-17.8333,-149.2667,Vanira Lodge
98,Guanica,PR,81.21,overcast clouds,17.9716,-66.9080,Copamarina Beach Resort & Spa
184,Cayenne,GF,77.09,overcast clouds,4.9333,-52.3333,Hôtel Le Dronmi
411,Koumac,NC,83.86,few clouds,-20.5667,164.2833,Le Monitel

In [17]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [20]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>


"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

In [21]:
# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]
# 11a. Add a marker layer for each city to the map. 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))